services:
  ps2smb:
    image: edisnord/ps2smb-server:3
    ports:
      - "${SMB_PORT}:445"
    volumes:
      - type: bind
        source: $OPL_SMB_DIR
        target: /mount

  pyoplm:
    build: ./PyOPLM-image
    command: $INPUT
    volumes:
      - type: bind
        source: $OPL_SMB_DIR
        target: /mnt
    environment:
        PYOPLM_OPL_DIR: /mnt

